AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: luckalot-scheduler stack

Parameters:
  AppName:
    Type: String
    Default: luckalot-scheduler
  StageName:
    Type: String
    Default: dev
    AllowedValues: [dev, ppe, prod]
    ConstraintDescription: must specify dev, ppe or prod
  LuckalotApiStackName:
    Type: String
    Default: luckalot-api-stack
  LuckalotSanookApiStackName:
    Type: String
    Default: luckalot-sanook-api-stack

Resources:  
  ScheduledEventImportResult:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [!Ref AppName, import-result-function]]
      Runtime: nodejs12.x
      CodeUri: import-result/
      Handler: app.lambdaHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(5 7 30,31,1,2,15,16,17 * ? *)
      MemorySize: 1024
      Timeout: 100
      Environment:
        Variables:
          LUCKALOT_API_HOST:
            Fn::ImportValue:
              !Sub "${LuckalotApiStackName}-ApiGatewayUrl"
          LUCKALOT_SANOOK_API_HOST:
            Fn::ImportValue:
              !Sub "${LuckalotSanookApiStackName}-ApiGatewayUrl"
